### ISSUE TITLE
Settle open orders accounts

### ISSUE THREAD

**Issue by metaproph3t** [Dodecahedr0x/meta-dao-frontend#26]
We should settle the open orders accounts using [this function](https://github.com/openbook-dex/openbook-v2/blob/b70cac715febb50fa41e8d75eab95acacac7657a/programs/openbook-v2/src/lib.rs#L493) so that users don't end up with money stuck in these

**Comment by R-K-H** [comment]
See #24 as I've got the function built and it just needs some love to solve which accounts go where.

**Comment by R-K-H** [comment]
So this works for each individual account... Not sure if there's a batch or sweep... Otherwise this is tentatively marked as done.
