### ISSUE TITLE
[frontend] bug on connection - cross origin

### ISSUE THREAD

**Issue by stayrar3** [Dodecahedr0x/meta-dao-frontend#38]
Solflare from Firefox, could change if it's an isolated bug just for me. 

Happens when trying to go into the "trade", not before. 

<img width="1338" alt="Captura de Pantalla 2023-11-22 a la(s) 17 58 52" src="https://github.com/Dodecahedr0x/meta-dao-frontend/assets/85634299/d524011d-8ef9-4c9a-af07-b5544d53e5e0">

**Comment by metaproph3t** [comment]
can you try again?

**Comment by stayrar3** [comment]
Getting source map error. 

I´ll try later from chrome but need to set it up

<img width="1299" alt="Captura de Pantalla 2023-11-23 a la(s) 11 08 19" src="https://github.com/Dodecahedr0x/meta-dao-frontend/assets/85634299/66c4f855-5792-48af-8695-f3d7c1ca8d73">

**Comment by R-K-H** [comment]
I think this is resolved?

**Comment by stayrar3** [comment]
YES!
