### ISSUE TITLE
[feature] prevent trade action, before mint / token account creation

### ISSUE THREAD

**Issue by R-K-H** [Dodecahedr0x/meta-dao-frontend#57]
I'm imagining something like the below screenshot, where if you don't at the very least have the conditional token accounts for this then you'll need to create them before you trade. This will prevent any janky behavior and ensure that the user doesn't end up having to create them on settlement.

Arguably this likely could be circumvented with the construction of transaction such that these things happen depending on the user state, I'm just not that skilled in TX construction / what happens if certain thing fails?

<img width="307" alt="Screenshot 2023-11-24 at 4 23 20 PM" src="https://github.com/Dodecahedr0x/meta-dao-frontend/assets/1007667/e0b53472-5b01-4165-a610-d7543f5e24d6">

**Comment by Dodecahedr0x** [comment]
I think that users should not be bothered with token accounts so I feel like displaying buttons for that might make the user confused. A user who has no token accounts can't trade anyway, so I'd rather create all associated accounts silently when settling, as in issue #70
